name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Hello World
      id: hello-world
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Hello World
        setup-command: "./setup.sh"
        command: "./test/run.sh"
        timeout: 10
        max-score: 100000000
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        HELLO-WORLD_RESULTS: "${{steps.hello-world.outputs.result}}"
      with:
        runners: hello-world
